version: '3.7'

services:
  frontend:
    mem_limit: 128m
    cpus: 0.1

    restart: unless-stopped
    image: asuzas/uekfrontend:1.0.3
    container_name: frontend_sky
    env_file: .env
    depends_on:
      - backend
    ports:
      - 8094:80
  