name: CICD

on: 
  push

jobs:
  hello_world:
    name: print Hello World
    runs-on: ubuntu-latest
    steps:
      - name: print Hello World
        run: echo "Hello World!"

      - name: print Secret
        run: echo ${{secrets.MY_SECRET}}


      - uses: actions/checkout@v2

      - name: set executable sh
        run: chmod +x ./run.sh
        shell: bash

      - name: run sh
        run: ./run.sh
        shell: bash

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: echo “Hello World”
