name: CICD

on: 
  push

jobs:
  hello_world:
    name: print Hello World
    runs-on: ubuntu-latest
    steps:
      - name: print Hello World
        run: echo "Hello World!"

      - name: print Secret
        run: echo ${{secrets.MY_SECRET}}


      - uses: actions/checkout@v2

      - name: set executable sh
        run: chmod +x ./run.sh
        shell: bash

      - name: run sh
        run: ./run.sh
        shell: bash

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: echo “Hello World”

      - name: copying remote shell script using password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: ./run.sh
          target: .

      - name: executing remote shell script using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: ./run.sh

  test_backend_gradle:
    name: run gradle tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@18
        with:
          java-version: 18
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test