name: CICD

on: 
  push

jobs:
  hello_world:
    name: print Hello World
    runs-on: ubuntu-latest
    steps:
      - name: print Hello World
        run: echo "Hello World!"

      - name: print Secret
        run: echo ${{secrets.MY_SECRET}} 